services:
  # Backend API
  - type: web
    name: task-manager-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend
  - type: web
    name: task-manager-web
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-manager-api.onrender.com
      - key: NODE_ENV
        value: production 